### Find all films with pagination queries
# GET /films
# Sends an array of films.
GET {{localBaseUrl}}/films
?limit=10
&page=1
&orderBy=nameAsc

### Find a single film
# GET /films/:slug
# Sends a single film with Article, Person, Studio, Tag relations
GET {{localBaseUrl}}/films/test-slug