### Find all feature articles with pagination queries
# GET /features
# Sends an array of features.
GET {{localBaseUrl}}/features
?limit=25
&page=1
&orderBy=nameAsc

### Find recent features
# GET /features/recent
# Sends the most recently created features.
GET {{localBaseUrl}}/features/recent

### Find a single feature
# GET /features/:slug
# Sends a single feature with Article relations.
GET {{localBaseUrl}}/features/corriganville