### Find all persons with pagination queries
# GET /people
# Sends an array of persons.
GET {{localBaseUrl}}/people
?limit=10
&page=1
&orderBy=lastNameAsc

### Find a single person
# GET /people/:slug
# Sends a single film with relations
GET {{localBaseUrl}}/people/ray-crash-corrigan