### Find all persons with pagination queries
# GET /people
# Sends an array of persons.
GET {{localBaseUrl}}/people
?limit=25
&page=1
&orderBy=lastNameAsc

### Find recent people
# GET /people/recent
# Sends array of recent people
GET {{localBaseUrl}}/people/ray-crash-corrigan

### Find a single person
# GET /people/:slug
# Sends a single film with relations
GET {{localBaseUrl}}/people/ray-crash-corrigan